name: 'Profile Readme Development Stats'
author: aboba
description: 'test'

inputs:
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    required: true
    default: ${{ github.token }}

  WAKATIME_API_KEY:
    description: 'Your Wakatime API Key'
    required: true

runs:
  using: 'docker'
  image: .